Name:           ros-hydro-scheduler
Version:        0.0.1
Release:        2%{?dist}
Summary:        ROS scheduler package

Group:          Development/Libraries
License:        MIT
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-mongodb-store
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-scipoptsuite
Requires:       ros-hydro-strands-executive-msgs
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-mongodb-store
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-scipoptsuite
BuildRequires:  ros-hydro-strands-executive-msgs

%description
A task scheduler implemented using mixed integer programming.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Oct 29 2014 Nick Hawes <n.a.hawes@cs.bham.ac.uk> - 0.0.1-2
- Autogenerated by Bloom

* Fri Oct 24 2014 Nick Hawes <n.a.hawes@cs.bham.ac.uk> - 0.0.1-1
- Autogenerated by Bloom

* Fri Oct 24 2014 Nick Hawes <n.a.hawes@cs.bham.ac.uk> - 0.0.1-0
- Autogenerated by Bloom

